name: Process Submitted Package(s)

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        required: true
        type: string
      distribution:
        required: true
        type: string
      repository:
        required: true
        type: string
      run_id:
        required: true
        type: string

concurrency:
  cancel-in-progress: false
  group: apt-commit-queue

jobs:
  process_submitted_packages:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SFG_APT_REPO_UPLOADER_APP_ID }}
          private-key: ${{ secrets.SFG_APT_REPO_UPLOADER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Download Submitted Package(s)
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh run download ${{ inputs.run_id }} \
            --repo ${{ inputs.repository }} \
            --name ${{ inputs.artifact_name }} \
            --dir "./submitted_packages"

      - name: Verify Artifact Attestation and Origin
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          json=""
          package_count=0

          for package in "./submitted_packages/"*.deb; do
            [ -e "${package}" ] || continue

            echo "Verifying attestation for ${package}..."
            json=$(gh attestation verify "${package}" --repo "${{ inputs.repository }}" --format json)
            echo "Attestation verified for '$(basename "${package}")'."
            package_count=$((package_count + 1))
          done

          if [ "${package_count}" -eq 0 ]; then
            echo "No packages found in artifact. Exiting."
            exit 0
          fi

          # Extract the true Git ref from the SLSA provenance.
          ref=$(echo "${json}" | jq -r '.[0].verificationResult.statement.predicate.buildDefinition.externalParameters.workflow.ref')

          # Verify the origin of the artifact by looking at the last package's ref.
          if [[ "${ref}" == "refs/heads/"* ]]; then
              branch_name="${ref#refs/heads/}"
              echo "Checking protection status for branch: ${branch_name} in ${inputs.repository}"
              is_protected=$(gh api "repos/${inputs.repository}/branches/${branch_name}" --jq '.protected')
              
              if [ "${is_protected}" != "true" ]; then
                echo "Error: Branch '${branch_name}' is not a protected branch."
                exit 1
              fi

              echo "Branch '${branch_name}' is confirmed as protected."
            
            elif [[ "${ref}" == "refs/tags/"* ]]; then
              echo "Deployment triggered by a tag. Proceeding."
            else
              echo "Error: Unsupported ref format: ${ref}"
              exit 1
            fi

            echo "Artifact origin verified successfully."

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          lfs: true
          path: sfg_apt_repo

      - name: Commit Packages
        run: |
          distribution="${{ inputs.distribution }}"
          mkdir -p "sfg_apt_repo/packages/${distribution}"

          cd sfg_apt_repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          new_packages=0

          for package in "../submitted_packages/"*.deb; do
            [ -e "${package}" ] || continue

            package_name=$(basename "${package}")
            target_package_filepath="packages/${distribution}/${package_name}"
            
            if [ -f "${target_package_filepath}" ]; then
              echo "Error: Package '${package_name}' already exists! You must increment the version in your 'DEBIAN/control' file."
              exit 1
            fi
            
            echo "Adding package '${package_name}' to distribution '${distribution}'."
            cp "${package}" "${target_package_filepath}"
            git add "${target_package_filepath}"
            new_packages=$((new_packages + 1))
          done

          if [ "${new_packages}" -eq 0 ]; then
            echo "No packages found in artifact. Exiting."
            exit 0
          fi

          git commit -m "Add ${distribution} package(s) from ${{ inputs.repository }}" \
                     -m "Source Run: https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}"
          git push
