name: Upload Packages

on:
  workflow_call:
    inputs:
      package_artifact_name:
        description: The string name of the artifact uploaded by the caller workflow containing the package(s).
        required: true
        type: string
      distribution:
        description: The target Ubuntu distribution.
        required: true
        type: string
    secrets:
      SFG_APT_REPO_UPLOADER_APP_ID:
        required: true
      SFG_APT_REPO_UPLOADER_APP_PRIVATE_KEY:
        required: true

jobs:
  upload_packages:
    runs-on: ubuntu-22.04
    steps:
      - name: Download Packages From Caller
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.package_artifact_name }}
          path: ./packages

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SFG_APT_REPO_UPLOADER_APP_ID }}
          private-key: ${{ secrets.SFG_APT_REPO_UPLOADER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "sfg_apt_repo"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: "sfg-autonomous-systems/sfg_apt_repo"
          token: ${{ steps.generate-token.outputs.token }}
          path: "sfg_apt_repo"
          lfs: true

      - name: Commit Packages
        run: |
          mkdir -p "sfg_apt_repo/packages/${{ inputs.distribution }}"

          cd "sfg_apt_repo"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          number_of_new_packages=0

          # Loop through downloaded packages.
          for package in "../packages/"*.deb; do
            # Skip if no packages were found.
            [ -e "${package}" ] || continue
            
            package_name=$(basename "${package}")
            
            if [ -f "packages/${{ inputs.distribution }}/${package_name}" ]; then
              checksum_existing=$(sha256sum "packages/${{ inputs.distribution }}/${package_name}" | awk '{print $1}')
              checksum_new=$(sha256sum "${package}" | awk '{print $1}')

              if [ "${checksum_existing}" = "${checksum_new}" ]; then
                echo "Package ${package_name} already exists in 'packages/${{ inputs.distribution }}' with the same checksum. Skipping."
                continue
              else
                echo "Package ${package_name} already exists in 'packages/${{ inputs.distribution }}' but has a different checksum. Overwriting."
              fi
            fi  
            
            echo "Adding ${package_name} to packages."
            cp "${package}" "packages/${{ inputs.distribution }}/"
            git add "packages/${{ inputs.distribution }}/${package_name}"
            number_of_new_packages=$((number_of_new_packages + 1))
          done

          if [ "$number_of_new_packages" -eq 0 ]; then
            echo "No new packages to upload. Skipping commit."
            exit 0
          fi

          # Use a multi-line commit message to provide better audit logs.
          git commit -m "Upload ${{ inputs.distribution }} package(s) from ${{ github.repository }}." \
                     -m "Workflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                     -m "Artifact Name: ${{ inputs.package_artifact_name }}" || true
          git push
