name: Submit Packages
description: Attests, uploads, and dispatches built packages to the central SFG repository.

inputs:
  dispatcher_app_id:
    description: "The app ID for the dispatcher."
    required: true
  dispatcher_app_private_key:
    description: "The private key for the dispatcher."
    required: true
  distribution:
    description: "The target Ubuntu distribution (e.g. jammy, noble)."
    required: true
  path:
    description: "The path to the generated packages."
    required: true

runs:
  using: "composite"
  steps:
    # Based on https://docs.github.com/en/actions/how-tos/secure-your-work/use-artifact-attestations/use-artifact-attestations.
    - name: Generate Attestation
      uses: actions/attest@v4
      with:
        subject-path: ${{ inputs.path }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sfg-packages-${{ github.run_id }}
        path: ${{ inputs.path }}
        retention-days: 1

    - name: Generate Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.dispatcher_app_id }}
        private-key: ${{ inputs.dispatcher_app_private_key }}
        owner: ${{ github.repository_owner }}
        repositories: "sfg_apt_repo"

    - name: Dispatch Event to Process Submitted Package(s)
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        gh workflow run process_submitted_packages.yaml \
          --repo sfg-autonomous-systems/sfg_apt_repo \
          -f artifact_name="sfg-packages-${{ github.run_id }}" \
          -f distribution="${{ inputs.distribution }}" \
          -f ref="${{ github.ref }}" \
          -f repository="${{ github.repository }}" \
          -f run_id="${{ github.run_id }}"
